### ISSUE TITLE
May not be using this correctly?

### ISSUE THREAD

**Issue by elliotth30** [BitsAndDroids/FlightConnector-Rust#109]
[3_Displaying-Data.zip](https://github.com/BitsAndDroids/Bits-and-Droids-flight-connector/files/14971485/3_Displaying-Data.zip)

Apologies if this is completely wrong, but I followed one of your videos where you create a speed dial and I am doing something similar. I just wanted to test out output from the software to an Arduino. I expected the value to then be output to my display but only get the reading 0 so have no idea if the data is being passed or if it is on the code side.

I am using the new Rust connector and have a profile setup with "indicated altitude" being output - or if I am not handling it correctly in the code.

Below is my very simple code:

`#include <BitsAndDroidsFlightConnector.h>
#include <TM1637Display.h>

//We create a connector object to send and receive commands
BitsAndDroidsFlightConnector connector = BitsAndDroidsFlightConnector();

// Define the connections pins:
#define CLK 2
#define DIO 3

// Create a TM1637Display object:
TM1637Display display(CLK, DIO);

int altitude = 1234; // You can replace this with any variable or sensor data

void setup() {
  pinMode(LED_BUILTIN, OUTPUT);
  digitalWrite(LED_BUILTIN, LOW);
  
  Serial.begin(115200);
  
  // Set the display's brightness (0 to 7):
  display.setBrightness(0x0f); // Set brightness to maximum
  displayNumber(altitude);
  delay(1000);
}

void loop() {
  
  altitude = int(connector.getIndicatedAltitude());

  // Display the number
  displayNumber(altitude);

  // Check if there is data
  if (altitude > 1) {
    digitalWrite(LED_BUILTIN, HIGH);
  } else {
    digitalWrite(LED_BUILTIN, LOW);
  }

  // Pause for a bit before updating the display again
  delay(100); // Update every second
}

void displayNumber(int num) {
  // Display the number on the TM1637
  display.showNumberDec(num, false); // 'true' to show leading zeros
}
`

Any help would be greatly appreciated.

**Comment by BitsAndDroids** [comment]
I'll have a look if I'm able to see what's happening (will be tomorrow or tuesday).

**Comment by BitsAndDroids** [comment]
@elliotth30 You're missing a single line in the loop.
If you add connector.dataHandling() your code should work.
```
#include <BitsAndDroidsFlightConnector.h>
#include <TM1637Display.h>

//We create a connector object to send and receive commands
BitsAndDroidsFlightConnector connector = BitsAndDroidsFlightConnector();

// Define the connections pins:
#define CLK 2
#define DIO 3

// Create a TM1637Display object:
TM1637Display display(CLK, DIO);

int altitude = 1234; // You can replace this with any variable or sensor data

void setup() {
pinMode(LED_BUILTIN, OUTPUT);
digitalWrite(LED_BUILTIN, LOW);

Serial.begin(115200);

// Set the display's brightness (0 to 7):
display.setBrightness(0x0f); // Set brightness to maximum
displayNumber(altitude);
delay(1000);
}

void loop() {
  connector.dataHandling();

altitude = int(connector.getIndicatedAltitude());

// Display the number
displayNumber(altitude);

// Check if there is data
if (altitude > 1) {
digitalWrite(LED_BUILTIN, HIGH);
} else {
digitalWrite(LED_BUILTIN, LOW);
}

// Pause for a bit before updating the display again
delay(100); // Update every second
}

void displayNumber(int num) {
// Display the number on the TM1637
display.showNumberDec(num, false); // 'true' to show leading zeros
}
```

**Comment by BitsAndDroids** [comment]
This line lets your Arduino listen for incoming messages from the connector.

**Comment by elliotth30** [comment]
Thank you very much, just gave this an update but unfortunately still no luck. I've popped it into the top of the loop(), do I need to initiate anything in the setup? - or does Serial need to not be specified or specified.

I noticed in one of your documentations from the older version that there is a baud rate, and in the rust version there is not. Could this also be my issue?

Thank you very much for your time.

**Comment by BitsAndDroids** [comment]
The baud rate is currently at 115200 (the line Serial.begin(115200)). This matches the connector speed, so it should be fine.  Did you create an output set with the indicated altitude as a variable? 
![image](https://github.com/BitsAndDroids/FlightConnector-Rust/assets/77780263/c03418aa-4479-4221-bb65-767e89f9ac54)
it should then look something like this:
![image](https://github.com/BitsAndDroids/FlightConnector-Rust/assets/77780263/19a334bc-fab3-4e5a-8905-54cc895e1e91)

**Comment by elliotth30** [comment]
This is my setup, but I see that you have a red dot next to yours that I am missing, could this be part of it?![PXL_20240414_181332631.jpg](https://github.com/BitsAndDroids/FlightConnector-Rust/assets/63171003/99e89bce-8966-4239-ace2-a4d08a0ad76f)

![PXL_20240414_181346334.jpg](https://github.com/BitsAndDroids/FlightConnector-Rust/assets/63171003/50f4acee-f8b2-4073-8eef-71cfd70eef5d)

**Comment by elliotth30** [comment]
To clarify in addition. I've not installed anything other than the rust app, and my code. Could it be that I am missing some sort of integration layer?

Also I've tried running as admin in case there was some sort of issue there.

**Comment by BitsAndDroids** [comment]
Make sure that no serial monitor is running (i.e. arduino ide). I've just added a new release that provides some extra visual feedback. A popup that a new update is available should be shown when restarting the app.
![image](https://github.com/BitsAndDroids/FlightConnector-Rust/assets/77780263/1cbfe26d-9595-487c-b961-2ca0d779b5fc)
if the circle in front of your com port is green, the connector can connect. if it turns red, the connection fails.

**Comment by BitsAndDroids** [comment]
To check if your Arduino is wired up correctly, you could also go to the Arduino IDE, open the serial monitor, and send a message that looks like 335 100. If everything is wired up correctly, your LCD should display 100 (or 200 if you replace the number).

**Comment by elliotth30** [comment]
Amazing thank you very much! I haven't tried on my main pc yet, but can confirm the wiring is correct and received the serial perfectly so that's a start! I'm actually using my PC which I don't use for anything except the game. So could be some random software for a while back interfacing with the ports.

I appreciate the format, so {Command Code} {integer response} is that the same for all? With spaces between or as new lines?

Would it be possible in future releases to have some log/terminal output through a menu or button? So that users can view the commands coming out without running a dev build? Absolutely no problem if not and really really appreciate the tonnes of work that has evidently gone into this!

I was also wondering, do you plan on being able to export/load settings down the line?

**Comment by BitsAndDroids** [comment]
The logs are almost production-ready. Exporting/importing the settings will also come with a future update (is a minor feature that I'm able to port over from the old connector). Currently, the settings are all stored in %appdata%/bitsanddroids. Some logs are already present in this location (but nothing useful). All commands transmitted are formatted like {command code} {integer/float/string}/n (including a space ended with a linebreak). All command codes can be found in the docs https://bitsanddroids.github.io/FlightConnector-Rust/ch03-01-outputs.html

**Comment by elliotth30** [comment]
Amazing thank you very much! I haven't tried on my main pc yet, but can confirm the wiring is correct and received the serial perfectly so that's a start! I'm actually using my PC which I don't use for anything except the game. So could be some random software for a while back interfacing with the ports.

I appreciate the format, so {Command Code} {integer response} is that the same for all? With spaces between or as new lines?

Would it be possible in future releases to have some log/terminal output through a menu or button? So that users can view the commands coming out without running a dev build? Absolutely no problem if not and really really appreciate the tonnes of work that has evidently gone into this!

I was also wondering, do you plan on being able to export/load settings down the line?

**Comment by elliotth30** [comment]
Amazing, looking forward to it! So, I've just tried on my PC, I'm getting a green light, with the correct COM selected (there's only two, and one says Arduino but have tried both just in case).

The Arduino worked perfectly when commands were typed manually (thanks again for that info).

I tried viewing the com port and it seems that it has all the right hand shakes and baud rate gets set but no data gets sent.

My question is, is that because the connector is not recieving anything from MSFS or is it not communicating with board. Any suggestions?

I'm worried I've not connected the two properly? I.e have I installed your software properly? Ive seen a lot about the WASM (or similar) but I have not done that as mentioned earlier - but don't believe I need to for this build?

Thanks again ![screen_1.PNG](https://github.com/BitsAndDroids/FlightConnector-Rust/assets/63171003/41339441-0323-4e45-b8b9-1d263871d48b)

**Comment by BitsAndDroids** [comment]
The WASM should be entirely optional for your use case. In theory, no extra software/steps should be necessary. I'll try adding some extra logging to the app to see if you can spot the issue. I will post an update once it's implemented (sometime tomorrow). Thanks for the detailed screenshots.

**Comment by elliotth30** [comment]
Thank you very much! Greatly appreciated, I'm just glad my code works at this point. No problem at all, thanks for taking the time to help me out!

**Comment by BitsAndDroids** [comment]
A new release is being published (usually takes 20 minutes). I've added extra logs that can be found in the %appdata%/bitsanddroids/logs folder. It should now display what messages have been sent to your controller and whether or not the connector succeeded. 
![image](https://github.com/BitsAndDroids/FlightConnector-Rust/assets/77780263/da5b3724-0e1b-4976-8e0c-e953a0933334)

**Comment by elliotth30** [comment]
Thank you very much for the update, so after trying the new version - the log indicates that the COM port is connected but no data seems to be sent!

Could this be to do with the version type (1.36.2.0)

Or could even the installation type? I am using the game pass version that is installed through the Xbox Windows app. 

[Uploading screen_2.PNG …]()

As always thanks for the support.

**Comment by BitsAndDroids** [comment]
Would you be able to send the files located in the %appdata%/bitsanddroids folder. Perhaps I'm able to see what settings it's trying to load. The installation type shouldn't be an issue (im using the ms store version as well). Thanks for the feedback so far

**Comment by elliotth30** [comment]
[bitsanddroids.zip](https://github.com/BitsAndDroids/FlightConnector-Rust/files/15001912/bitsanddroids.zip)

No problem, here you go. Glad to hear its the version shouldn't be causing issues. Thanks again!

**Comment by BitsAndDroids** [comment]
That's precisely the issue. In your version, I've accidentally added two places where the bundle is saved. In the present and separately in the bundle's file. I've changed the behavior to only save the outputs in the bundle, which gets referenced by the preset. That way, your changes will always be reflected if you update the bundle.

**Comment by elliotth30** [comment]
Thank you very much! Never been so happy to see some numbers on a little screen! The logout is great - super super useful and super intuitive to see the serial command being sent.

![screen_3.PNG](https://github.com/BitsAndDroids/FlightConnector-Rust/assets/63171003/2a32d55c-a42d-4c54-8050-d5067106e39e)

I was wondering if you'd like, at some point I'd be happy to write some different sketch examples for your documentation to show different inputs, outputs and combinations? No problem if not as I can see you're already working your way round.

Looking forward to creating some motorised displays, thanks again! I'm sure I am going to spend more time making than actually playing haha.

Thanks for all your work and support!

**Comment by BitsAndDroids** [comment]
I'm glad you got it working. Thanks for your patience and help in debugging this issue. I want you to know that all help writing examples is welcome and may help others in the future.
Looking forward to seeing you parked in mfs2020
