### ISSUE TITLE
Library generator generates blank .h file

### ISSUE THREAD

**Issue by Xenomorphologist** [BitsAndDroids/FlightConnector-Rust#286]
**Describe the bug**
I don't know if I'm doing something wrong, but the .h file generated by the library generator is always blank.

**To Reproduce**
1. Generate library under Arduino/libraries
2. Check .h file

**Screenshots**
<img width="599" alt="image" src="https://github.com/user-attachments/assets/960d1f96-f9b7-491f-942e-c942667bfe62">
<img width="590" alt="image" src="https://github.com/user-attachments/assets/c03556d3-5310-4cdc-958e-59cbdc549b44">

**Comment by BitsAndDroids** [comment]
Thank you for the report. I'll take a look tomorrow and will report back.

**Comment by BitsAndDroids** [comment]
![image](https://github.com/user-attachments/assets/7dfa252a-915c-4351-9a8f-54bbed42df4f)

Spend an hour looking at this. Accidentally put an extra y connectorY_library.... Release is being made and will be out in a few minutes.

**Comment by Xenomorphologist** [comment]
It works now, thank you!
